### ISSUE TITLE
Handling event colours

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#22]
COREMEDIA_PrimalGameData_BP's MasterDyeList is an array of the 26 in-game dyes. They correspond strikingly well with the 20-ish known event colours listed on the wiki so far.

Looks like they map onto/override colour IDs 201 upwards.

**Comment by VolatilePulse** [comment]
To expand on the information, the following ranges appear to be completely consistent, pending testing on a mod that adds additional dye colors:
- 0 is reserved for the "nude" color (applies no color, showing the texture only)
- 1-200 is reserved for "Dino" colors defined in the PrimalGameData asset in the ColorDefinitions property
- 201 - 255 is reserved for "Dye" colors

All mods inherit from the COREMEDIA_PrimalGameData asset and uses the ColorDefinitions array defined within unless overridden. If a mod adds custom colors, the DevKit will create a ColorDefinitions array that includes the current official colors first with the new colors appended. In the example of Primal Fear currently, the first 56 colors are official with the 57-150 colors being custom colors defined by the mod. A mod that adds no new colors will always the official ColorDefinitions, even if the mod was last updated a year before the official definition is increased to contain more colors. However, a mod like Primal Fear that has the color array defined in its asset will be stuck with those 150 colors unless an update for the mod is released after the official color array is changed.

Depending on the mod order, the order of colors can vary drastically. As only a max of 200 colors are able to be set by the ColorDefinitions, at most the first 4 mods are the only ones that can contribute to available colors. For example, if Primal Fear is first on the list followed by another mod, you will get the following color IDs:
- 1 - 56 Official Colors
- 57 - 150 Custom Primal Fear Colors
- 151 - 200 First 50 Official Colors

If you have Primal Fear second in the mod order, you would see:
- 1 - 56 Official Colors
- 57 - 112 Official Colors
- 113 - 200 First 88 Custom Primal Fear Colors

Changing the mod order can alter the existing colors on creatures in game based on Ark storing colors as the ColorID that directly corresponds to the ColorDefinitions array index. This index is generated based on the colorsets for a species. The colorset uses ColorNames for potential colors to spawn with and will search the ColorDefinitions array for all matching strings. For example, a colorset that has the "Red" color listed that's selected will normally just result in an ID of 1 (corresponds with official color IDs). However when multiple mods with no custom colors (for the sake of argument), that color ID could be 1, 57, 113, or 169. If the creature ended up with the ID of 113 and the Primal Fear mod is added to the first slot, that creature will end up with a drastically different color.

The final note is that a creature can only get a ColorID as long as the Color Name it looks for actually exists within the ColorDefinitions array. From official colorsets, some ColorNames are spelled incorrectly and that species can never spawn with those colors. On the other end of the spectrum, if Primal Fear is further down in the mod order, many of its creatures can not spawn with the custom colors as they simply wouldn't exist in the ColorDefinitions array.

**Comment by VolatilePulse** [comment]
A Wiki page should still be created outlining the information gather in regards to how colors are selected during creature spawn and mutations as well as how they stack with mods and how mods can override official colors as well as the dye list being modified by mods.

Proposed solution for handling colors more accurately is to create a "colors" property for the color definitions of a mod, change the color regions to first only contain the region name and then replace the color ID with a color definition name so it can be looked up once we properly handle color stacking with mod stacking.

**Comment by coldino** [comment]
When this is implemented we should discuss improving the export formatting with @cadon. 

For one thing, we absolutely need to move away from numeric IDs.

**Comment by coldino** [comment]
...and include colour set weights as per cadon/ARKStatsExtractor#928.

**Comment by cadon** [comment]
Sometimes it feels like the ARK devs are trying to make these things extra challenging.

Export files give us (not regular) RGBA-values for each color-region. If you can extract the mod-color-definitions, we can create a lookup-table with a hash-key (`(R.ToString() + G.ToString() + B.ToString()).GetHashCode()`) and Color-objects as values to assign the colors fast. Maybe a hash is better than arbitrary color-names?

The linked issue is about the stat-colors, not the species-region-colors.

**Comment by VolatilePulse** [comment]
The wiki page for [Ark colors](../wiki/Colors) has been added to document our observations and data discovered. While it is a WIP, most of the information is complete with some limited testing still required, specifically with the `MasterDyeList` and mods. While event colors haven't been definitely answered yet (due to lack of source code of Ark), I'm content with my observations as well as information gathered from players and modders.

In regards to moving away from numeric IDs, that was implemented with 8aac7c1a64a4ed0427242db96694317a6c1dec15. It appears to be matured, but it should be noted that `ColorNames` should not be assumed to exist in the color definitions array as they are hand typed strings and some contain typos or reference colors from other mods.

In response to @cadon, as detailed in the above wiki page, the color sets and definitions can vary rather drastically. While I don't believe the request is unreasonable, I don't believe it would result in reliable behavior. @coldino also implemented the `ColorRegion` name replacement based on the information you provided him with bc7cf2405005e520eb0f5da5cb5e9636045b7b24. The [overrides.yaml](../blob/master/config/overrides.yaml) file currently contains all of the overrides provided and more can be added at any time.

I figure this issue is resolved unless more information comes to light or a change to formatting is desired.
