### ISSUE TITLE
Develop and test name-based species discovery system

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#3]

**Comment by VolatilePulse** [comment]
Species missing the descriptive have been able to be spawned, but were immediately destroyed by the game. This is likely due to the species having specific criteria for spawn regions as the "/Game/Extinction/Dinos/KingKaiju/Minions/Corrupt_Arthro_Character_BP" that was tested is likely only to be spawned in a boss arena or close to a boss.

The DescriptiveName is used to generate the Species Name, which is typically displayed in the creature's inventory, but it didn't persist long enough to look in it's inventory.

This is not definitive proof DescriptiveName is required for a species to remain spawned in, but rather that it meets the minimum criteria for at least spawning an asset in Ark. Numerous mods and vanilla have a few species without a DescriptiveName and should be tried to get a better understanding of what's going on.

In regards to the points raised, I believe we should be looking for an alternative species name if the descriptive name is blank, like the class name, so it's quickly identifiable when viewed in a list of descriptive names.
While I have had no luck discovering "unspawnables" based on a single property or lack thereof, it does appear there are a few other requirements than just the DCSC and Character components. This may take some time to iron out, but some species that inherit from defunct mods or assets fail to spawn, likely due the asset building system encountering an error and aborting.

It would be nice to get lists of creatures that meet X requirements but don't spawn, unfortunately the list would be rather long and take quite some time to work through.
